[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "daikin_cycle_ml"
version = "0.8.0"
requires-python = ">=3.12"

[tool.pytest.ini_options]
markers = [
    "expected_lingering_tasks: mark test that expects lingering tasks (phcc)",
    "expected_lingering_timers: mark test that expects lingering timers (phcc)",
]
asyncio_mode = "auto"
testpaths = ["tests"]
addopts = "-q --cov=custom_components.daikin_cycle_ml --cov-fail-under=95"
